# Generated by Django 5.2.11 on 2026-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklanganmi?')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
